name: Build Guides

on:
  push:
    branches-ignore: [ 'temp/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-guides:
    name: Build FMI Guides

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: prepare
      run: mkdir build && mkdir build/fmi-guide && mkdir build/fmi-profiles && mkdir build/ls-bus-guide
    - name: build implementers guide
      uses: avattathil/asciidoctor-action@master
      with:
        program: "asciidoctor -D build/fmi-guide --backend=html5 --attribute=revnumber=${GITHUB_REF#refs/heads/}-$GITHUB_SHA --attribute=revdate=$(date +%F) fmi-guide/index.adoc"
    - name: build FMI profiles
      uses: avattathil/asciidoctor-action@master
      with:
        program: "asciidoctor -D build/fmi-profiles --backend=html5 --attribute=revnumber=${GITHUB_REF#refs/heads/}-$GITHUB_SHA --attribute=revdate=$(date +%F) fmi-profiles/index.adoc"
    - name: copy images
      run: tar cf - fmi-guide/images fmi-profiles/images | tar xfC - build
    - name: add redirects for old content
      uses: ActionCloud/generate-redirects@v1
      with:
        target: build/ls-bus-guide
        links: |
          {
            "index": "https://modelica.github.io/fmi-ls-bus-guides/main/ls-bus-guide/"
          }
    - name: archive implementers guide
      uses: actions/upload-artifact@v4
      with:
        name: FMI-Guide
        path: build/fmi-guide/*
        if-no-files-found: error
    - name: archive FMI profiles
      uses: actions/upload-artifact@v4
      with:
        name: FMI-Profiles
        path: build/fmi-profiles/*
        if-no-files-found: error
    - name: extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
    - name: deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        destination_dir: ${{ steps.extract_branch.outputs.branch }}
        enable_jekyll: true
